import os
import sys
import torch
from torch.utils.data import DataLoader
from torchvision import transforms
from transformers import AutoTokenizer
from torch.optim import AdamW
from torch.optim.lr_scheduler import CosineAnnealingLR
from tqdm import tqdm

import sys
if sys.stdout and hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding='utf-8')

from dataset import KvasirVQADataset
from model import EndoReportGenerator

from endofm_vision_encoder import vit_base

def load_endofm(checkpoint_path, device):
    print(f"Loading EndoFM-LV from {checkpoint_path}...")
    try:
        # Initialize model based on the standard architecture of EndoFM (ViT Base)
        model = vit_base(patch_size=16, num_classes=0) 
        state_dict = torch.load(checkpoint_path, map_location='cpu', weights_only=False)
        
        # Handle checkpoint keys (e.g., generated by DINO pretraining)
        if 'student' in state_dict:
            state_dict = state_dict['student']
        elif 'model' in state_dict:
            state_dict = state_dict['model']
            
        clean_state_dict = {}
        for k, v in state_dict.items():
            k = k.replace("module.", "").replace("backbone.", "")
            clean_state_dict[k] = v
            
        model.load_state_dict(clean_state_dict, strict=False)
        model.to(device)
        model.eval() # Must be in eval mode
        return model
    except Exception as e:
        print(f"Error loading model: {e}. Please double-check the architecture.")
        return None

def main():
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"Using device: {device}")
    
    # 1. Prepare Vision Encoder (EndoFM-LV)
    checkpoint_path = "checkpoints/endofm_lv.pth"
    vision_encoder = load_endofm(checkpoint_path, device)
    
    # 2. Tokenizer & LLM
    llm_name = "Qwen/Qwen2.5-7B-Instruct" 
    tokenizer = AutoTokenizer.from_pretrained(llm_name)
    tokenizer.pad_token = tokenizer.eos_token
    
    # 3. Initialize Global Model
    # vision_dim for ViT-Base is 768. 
    model = EndoReportGenerator(
        vision_encoder=vision_encoder,
        llm_model_name_or_path=llm_name,
        vision_dim=768
    ).to(device)
    
    # 4. Dataset & DataLoader
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.RandomHorizontalFlip(),
        transforms.ColorJitter(brightness=0.2, contrast=0.2),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
    ])
    
    base_dir = "kvasir_vqa_1000"
    train_dataset = KvasirVQADataset(
        json_path=os.path.join(base_dir, "train", "dataset.json"),
        image_dir=os.path.join(base_dir, "train"),
        transform=transform,
        tokenizer=tokenizer,
        max_length=128
    )
    
    train_loader = DataLoader(train_dataset, batch_size=1, shuffle=True)
    gradient_accumulation_steps = 8 # Target effective batch size 32 (we use 16 for memory safety, or 32 if VRAM permits)
    
    # 5. Optimizer (Train Mapping Network & LoRA)
    trainable_params = [p for p in model.parameters() if p.requires_grad]
    optimizer = AdamW(trainable_params, lr=2e-5, weight_decay=0.01)
    
    # 6. Training Loop
    epochs = 4
    scheduler = CosineAnnealingLR(optimizer, T_max=epochs)
    
    for epoch in range(epochs):
        model.train()
        total_loss = 0
        progress = tqdm(train_loader, desc=f"Epoch {epoch+1}/{epochs}")
        for step, batch in enumerate(progress):
            
            pixel_values = batch["pixel_values"].to(device)
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)
            
            outputs = model(
                pixel_values=pixel_values,
                input_ids=input_ids,
                attention_mask=attention_mask,
                labels=labels
            )
            
            # Gradient Accumulation
            loss = outputs.loss / gradient_accumulation_steps
            loss.backward()
            
            if (step + 1) % gradient_accumulation_steps == 0 or (step + 1) == len(train_loader):
                # Gradient clipping to stabilize loss
                torch.nn.utils.clip_grad_norm_(trainable_params, max_norm=1.0)
                optimizer.step()
                optimizer.zero_grad()
            
            total_loss += (loss.item() * gradient_accumulation_steps)
            progress.set_postfix({"loss": loss.item() * gradient_accumulation_steps})
            
        scheduler.step()
        print(f"Epoch {epoch+1} Average Loss: {total_loss / len(train_loader):.4f}")
        
        # Save Checkpoint EVERY EPOCH (Includes both Mapping Network and LoRA)
        epoch_dir = f"checkpoints/epoch_{epoch+1}"
        os.makedirs(epoch_dir, exist_ok=True)
        torch.save(model.mapping_network.state_dict(), f"{epoch_dir}/mapping_network.pth")
        model.llm.save_pretrained(f"{epoch_dir}/lora_weights")
        print(f"Saved checkpoint to {epoch_dir}")
        
    print("Training completed!")

if __name__ == "__main__":
    main()
